### ISSUE TITLE
Fix interrupt handlers

### ISSUE THREAD

**Issue by Menotdan** [wsKilljoy/wos#2]
Your interrupt handlers from the tutorial have a widely known bug where the interrupt state is not passed as a pointer and that causes a problem where the compiler might trash those values and cause your code to break.

**Comment by wsKilljoy** [comment]
No longer valid as the main branch is now using my rust codebase.

**Comment by Menotdan** [comment]
> No longer valid as the main branch is now using my rust codebase.

Are you sure that the rust codebase uses pointers instead of passing the entire struct? Rust still has to compile down to binary code, so the Rust code might do the same thing as the tutorial.
